[javadocs] Fix javadocs clearing all warnings
mathieucarbou/license-maven-plugin pull request #579
Opened 2023-05-29 20:07 UTC by hazendaz

Resolves all javadoc warnings to console that are a result of failure to comply with requested setup of same.

This does not resolve one left over item where the link is being redirected to jdk 20 but makes the output of the build finally in most reasonable state.

2023-05-30 07:05 UTC, mathieucarbou requested changes

2023-05-30 07:05 UTC, mathieucarbou commented on license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/document/Document.java
> +   */
please remove all the javadoc not bringing any information.

2023-05-30 07:05 UTC, mathieucarbou commented on license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/document/DocumentType.java
> +  /** The scss. */
please don't add javadoc if you don't document.... This does not bring any information.

2023-06-08 01:16 UTC, hazendaz commented
converted to draft so these can be better written out to be useful.  the core reason was to remove the 100s of warnings at maven.  keeping in draft will avoid accidental merging until work can later be completed.

2023-06-08 06:06 UTC, mathieucarbou commented
> converted to draft so these can be better written out to be useful. the core reason was to remove the 100s of warnings at maven. keeping in draft will avoid accidental merging until work can later be completed.

I understand the reason, but that's not a good fix ;-) This is a plugin so I would suggest either we remove the javadoc from everywhere except the plugin metadata (and convert existing doc to internal doc with `//`), or we correctly add the javadoc. And if some warnings require to be ignored at the javadoc plugin itself, then let's ignore them, globally or per file.

2023-08-26 20:04 UTC, hazendaz commented
closing for now to prevent noise as I rebase branches locally on my end.  Will reopen once appropriate work done here.

2023-08-26 20:04 UTC, closed without merging